In [5]:
import numpy as np

In [2]:
a = np.array(1)
a


array(1)

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(5,)

In [6]:
b= np.array(2)

In [9]:
b = np.array([(1,2,3,4),(3,4,5,6)])
b

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [10]:
b.shape


(2, 4)

In [11]:
a = np.array([[1]])

In [12]:
a.ndim

2

# Different Ways of creating Array

In [13]:
c = np.ones(4)
c

array([1., 1., 1., 1.])

In [17]:
c = np.ones((4,2))
c

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
d = np.zeros((5,5))
d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Indexing & Slicing

In [20]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [21]:
a[3]

4

In [22]:
a[-2]

3

In [23]:
len(a)

4

In [24]:
e = np.arange(10,70,2) #start , end , jump
e

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68])

In [25]:
f = np.arange(70,10,-4)
f

array([70, 66, 62, 58, 54, 50, 46, 42, 38, 34, 30, 26, 22, 18, 14])

In [27]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [28]:
a[1:5]

array([2, 3, 4, 5])

In [29]:
a[-1:1]

array([], dtype=int32)

In [30]:
a[-4:-1]

array([3, 4, 5])

In [31]:
a[-4:0]

array([], dtype=int32)

In [32]:
a[1:-2]

array([2, 3, 4])

In [33]:
a[:]

array([1, 2, 3, 4, 5, 6])

In [34]:
a[::-1]

array([6, 5, 4, 3, 2, 1])

In [8]:
a=np.arange(36).reshape(6,6)

In [9]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [11]:
a[-3,]#[row,coloumn]

array([18, 19, 20, 21, 22, 23])

In [12]:
a[:,1]

array([ 1,  7, 13, 19, 25, 31])

In [16]:
a[:,1:3]

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [20]:
a[3,2:5]

array([20, 21, 22])

In [24]:
a[2,3:]

array([15, 16])

In [25]:
a[2:,:2]

array([[12, 13],
       [18, 19],
       [24, 25],
       [30, 31]])

In [32]:
a[3:5,:4]

array([[18, 19, 20, 21],
       [24, 25, 26, 27]])

In [35]:
a[3:5,2:]

array([[20, 21, 22, 23],
       [26, 27, 28, 29]])

In [36]:
a[1:3,:2]

array([[ 6,  7],
       [12, 13]])

In [37]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

# Array Operation

In [40]:
a1=np.identity(5)
a1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.transpose(a1)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.transpose(a)

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [60]:
b = np.array([(1,2,3,4,6,7),(3,4,5,6,6,7)])
b

array([[1, 2, 3, 4, 6, 7],
       [3, 4, 5, 6, 6, 7]])

In [62]:
np.hsplit(b,6)

[array([[1],
        [3]]),
 array([[2],
        [4]]),
 array([[3],
        [5]]),
 array([[4],
        [6]]),
 array([[6],
        [6]]),
 array([[7],
        [7]])]

In [58]:
np.hstack([a1,a1])#horizontal stack

array([[1., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 1.]])

In [64]:
d= np.vstack([a1,a1])#vertical stack
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
d[::2]

array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [68]:
print(d+2*d+2)

[[5. 2. 2. 2. 2.]
 [2. 5. 2. 2. 2.]
 [2. 2. 5. 2. 2.]
 [2. 2. 2. 5. 2.]
 [2. 2. 2. 2. 5.]
 [5. 2. 2. 2. 2.]
 [2. 5. 2. 2. 2.]
 [2. 2. 5. 2. 2.]
 [2. 2. 2. 5. 2.]
 [2. 2. 2. 2. 5.]]


In [71]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [72]:
b = np.array([8,7,6,5])
b

array([8, 7, 6, 5])

In [73]:
a+b

array([9, 9, 9, 9])

In [74]:
a*b

array([ 8, 14, 18, 20])

In [76]:
2*a+4*b

array([34, 32, 30, 28])

In [79]:
(a+23)*(b+6)

array([336, 325, 312, 297])

In [80]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [81]:
b/2

array([4. , 3.5, 3. , 2.5])

In [82]:
b%a

array([0, 1, 0, 1])

In [84]:
a**b

array([   1,  128,  729, 1024])

# numpy.org

https://numpy.org/# 