In [114]:
! pip install opencv-python
import cv2
import numpy as np

In [117]:
image=cv2.imread(r"C:\Users\admin\Downloads\demo_face.jpg")
image
#image.ndim, .shape, .size

array([[[248, 248, 248],
        [248, 248, 248],
        [248, 248, 248],
        ...,
        [246, 246, 252],
        [246, 246, 252],
        [246, 246, 252]],

       [[248, 248, 248],
        [248, 248, 248],
        [248, 248, 248],
        ...,
        [247, 247, 253],
        [247, 247, 253],
        [247, 247, 253]],

       [[248, 248, 248],
        [248, 248, 248],
        [248, 248, 248],
        ...,
        [221, 221, 227],
        [221, 221, 227],
        [221, 221, 227]],

       ...,

       [[ 31,  42,  72],
        [ 36,  48,  76],
        [ 41,  53,  81],
        ...,
        [ 85,  74,  66],
        [ 80,  68,  58],
        [ 73,  60,  52]],

       [[ 36,  48,  76],
        [ 45,  58,  84],
        [ 39,  52,  78],
        ...,
        [ 64,  52,  46],
        [ 65,  52,  44],
        [ 65,  51,  45]],

       [[ 31,  44,  70],
        [ 35,  49,  72],
        [ 33,  47,  70],
        ...,
        [ 61,  49,  45],
        [ 69,  55,  49],
        [ 75,  60,  57]]

In [118]:
cv2.imshow(r"C:\Users\admin\Downloads\demo_face.jpg", image)
cv2.waitKey(0) # 100,1000, 10000
cv2.destroyAllWindows()

# Excercise 2- Image filter

In [ ]:
if image is None:
    print('Could not read image')

#Apply identity kernel
kernel1=np.array([[0.2,0,0],
                  [0,0.2,0],
                  [0,0,0.2]])

In [119]:
identity=cv2.filter2D(src=image, ddepth=-1,kernel=kernel1)
cv2.imshow('Og',image)
cv2.imshow('identity',identity)
cv2.waitKey()
cv2.imwrite('identity.jpg', identity)
cv2.destroyAllWindows()

In [109]:
a1=np.ones((5,5))
a1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#Apply blurring filter
kernel2=np.ones((5,5),np.float32)/25
img=cv2.filter2D(src=image,ddepth=-1,kernel=kernel2)

cv2.imshow('Og', image)
cv2.imshow('Kernel blur', img)
cv2.waitKey()
cv2.imwrite('identityblur_kernel.jpg', identity)
cv2.destroyAllWindows()

In [ ]:
b,g,r=cv2.split(image)

In [112]:
g

array([[208, 210, 212, ..., 222, 222, 220],
       [208, 210, 212, ..., 222, 222, 223],
       [208, 210, 212, ..., 223, 222, 222],
       ...,
       [154, 157, 159, ..., 212, 213, 214],
       [152, 154, 157, ..., 213, 214, 213],
       [150, 153, 155, ..., 213, 214, 214]], dtype=uint8)

In [ ]:
#20 // 2.3

In [ ]:
b =g//2

In [ ]:
#g

In [106]:
img=cv2.merge((b,g,r))
cv2.imshow('OG', img)
cv2.waitKey()
cv2.destroyAllWindows()
